### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by Matlik-Official** [aliinS/AjaHaldur#2]
Dashboardi loomine figmas antud disaini järgi

**Comment by aliinS** [comment]
react router.
sidebar ei laieneks.
kood ilusaks.

**Comment by Matlik-Official** [comment]
https://www.npmjs.com/package/react-router-dom

**Comment by aliinS** [comment]
make it responsive.
only 'dashboard' will get the 'active', when clicked.
when you click 'seaded' from sidebar and then accidentally click 'seaded' again, when already on "seaded" page then you will get an empty page. Why!?
